### ISSUE TITLE
High-level roadmap to 0.1.0

### ISSUE THREAD

**Issue by lazarljubenovic** [wane/wane#1]
- [ ] Polish and debug some `w:if` and `w:for` issues.
- [ ] Enable async code to update view (`setTimeout`, `setInterval`, a Promise-based `http`, probably no `async`/`await` at first).
- [ ] CSS, Sass and style encapsulation.
- [ ] Allow writing code in multiple files, add options to CLI and a config file.
- [ ] Write docs, examples and tutorials (probably only on GitHub at first, web site coming afterwards).
- [ ] Describe the high- and mid-level overview of how it all works. Keep this updated with every new optimization added later.
